Set sub = description.Create()
sub("type").value = "submit"
sub("name").value = "登陆"
sub("html tag").value = "INPUT"
Set password = description.Create()
password("type").value = "password"
password("name").value = "password"
password("html tag").value = "INPUT"
Set text = description.Create()
text("type").value = "text"
text("name").value = "username"
text("html tag").value = "INPUT"
Set thing = description.Create()
thing("text").value = "DANJIESHI2015夏季新款男士短袖T恤 男 韩版休闲修身V领透气半袖T恤衫"
thing("html tag").value = "A"
Set queding = description.Create()
queding("text").value = "确定"
queding("nativeclass").value = "Button"
Set jiarugouwuche = description.Create()
jiarugouwuche("text").value = "加入购物车"
jiarugouwuche("html tag").value = "A"
Set balance = description.Create()
balance("text").value = "去购物车结算"
balance("html tag").value = "A"
Set gobalance = description.Create()
gobalance("text").value = "去结算"
gobalance("html tag").value = "A"
Set checkbox = description.Create()
checkbox("type").value = "checkbox"
checkbox("html tag").value = "INPUT"
Set tijiao = description.Create()
tijiao("text").value = "提交订单"
tijiao("html tag").value = "A"
Set pingjiashouhou = description.Create()
pingjiashouhou("text").value = "评价/售后"
pingjiashouhou("html tag").value = "A"
Set pingjia = description.Create()
pingjia("text").value = "评价商品"
pingjia("html tag").value = "A"
Set submit = description.Create()
submit("type").value = "submit"
submit("name").value = "提交"
submit("html tag").value = "BUTTON"
Set textarea = description.Create()
textarea("type").value = "textarea"
textarea("name").value = "message"
textarea("html tag").value = "TEXTAREA"
Set star = description.Create()
star("name").value = "star"
star("html tag").value = "INPUT"